import math

print('Maior número inteiro sequente')
print(math.ceil(3.14))
print(math.ceil(4.0))
print('Número absoluto')
print(math.fabs(4))
print(math.fabs(-4))
print(math.fabs(-3.5))
print('Calcular o EXPONENCIAL')
print(math.exp(2))
print(math.exp(6))
print('Calcular log10')
print(math.log10(10))
print(math.log10(5))
print('Calcular potencia')
print(math.pow(2,5))
print(math.pow(4,2))
print('Calcular raiz')
print(math.sqrt(25))
print(math.sqrt(144))
print(math.sqrt(7))
print('Constantes matemáticas')
print('Contante PI')
print(math.pi)
print('Constante E')
print(math.e)